### PR TITLE
Initial support for Spark 3.1.2

### LINKED ISSUE #35: Upgrade Spark to 3.x series
We're using Spark 2.4 that is outdated & don't have many performance improvements. It's better to switch to Spark 3.x, and install PySpark via `pip` instead of "manual" download.

### PR DESCRIPTION
**Pull request by alexott**
Changes include:
* switch to `jupyter/pyspark-notebook:spark-3.1.2` image instead of manual install of Spark
* cleanup of Python dependencies
* switch to spark-solr 4.0.2 that supports Spark 3.1.2

Code wasn't checked yet

This will fix #35

### CODE REVIEW

**Comment by alexott** [comment]
I just made it building, but I need to make sure that examples are working with new Solr connector. Will start to test first chapters tomorrow

**Comment by alexott** [comment]
Ok, I rechecked chapters 3, 5 and 10, and everything works.  I also included changes for chapters 5 & 10 into this PR as the old PRs had merge conflicts.

**Comment by treygrainger** [comment]
Thanks @alexott! It seems to be working well, but it's resulting in lots of warnings and additional UI logging that's adding noise. I'm going through all the notebooks right now to verify that everything is working functionally, and (unless I find any issues) will probably go ahead and  merge and we can clean up those warnings afterward.

It's hard to deal with merge conflicts on Jupyter notebooks, so for sure better to go ahead and get this in since you've just gone through the effort to get it up to date with master.

**Comment by alexott** [comment]
@treygrainger is it possible to merge this one?

**Comment by treygrainger** [comment]
yep, sorry for the delay. I have a branch that fixes most of the issues I mentioned before. I'll get it pushed up on Sunday. I'll be doing work on the chapters all week next week, so will get this done first to prevent any subsequent merge conflicts.

**Pull request merged**
